package demo.buildingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Light")
@org.kie.api.definition.type.Description("Represents a Light in a Room")
@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
public class Light implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("id")
   private java.lang.String id;
   @org.kie.api.definition.type.Description("Room the building belongs to")
   @org.kie.api.definition.type.Label("Room")
   private demo.buildingmanagement.Room room;
   @org.kie.api.definition.type.Description("Current On/Off state")
   @org.kie.api.definition.type.Label("Current State")
   private java.lang.Boolean state;
   @org.kie.api.definition.type.Description("Current Level")
   @org.kie.api.definition.type.Label("Current Level")
   private java.lang.Float level;

   @org.kie.api.definition.type.Label("KWH Usage for the light")
   @org.kie.api.definition.type.Description("KWH usage for the lignt")
   private java.lang.Float kwhUsage;

   public Light()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public demo.buildingmanagement.Room getRoom()
   {
      return this.room;
   }

   public void setRoom(demo.buildingmanagement.Room room)
   {
      this.room = room;
   }

   public java.lang.Boolean getState()
   {
      return this.state;
   }

   public void setState(java.lang.Boolean state)
   {
      this.state = state;
   }

   public java.lang.Float getLevel()
   {
      return this.level;
   }

   public void setLevel(java.lang.Float level)
   {
      this.level = level;
   }

   public java.lang.Float getKwhUsage()
   {
      return this.kwhUsage;
   }

   public void setKwhUsage(java.lang.Float kwhUsage)
   {
      this.kwhUsage = kwhUsage;
   }

   public Light(java.lang.String id, demo.buildingmanagement.Room room,
         java.lang.Boolean state, java.lang.Float level, java.lang.Float kwhUsage)
   {
      this.id = id;
      this.room = room;
      this.state = state;
      this.level = level;
      this.kwhUsage = kwhUsage;
   }

}