package demo.buildingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OccupancySensor implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "id")
   private java.lang.String id;
   @org.kie.api.definition.type.Label(value = "Room")
   private demo.buildingmanagement.Room room;
   @org.kie.api.definition.type.Label(value = "Is Occupied")
   private java.lang.Boolean occupied;

   public OccupancySensor()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public demo.buildingmanagement.Room getRoom()
   {
      return this.room;
   }

   public void setRoom(demo.buildingmanagement.Room room)
   {
      this.room = room;
   }

   public java.lang.Boolean getOccupied()
   {
      return this.occupied;
   }

   public void setOccupied(java.lang.Boolean occupied)
   {
      this.occupied = occupied;
   }

   public OccupancySensor(java.lang.String id,
         demo.buildingmanagement.Room room, java.lang.Boolean occupied)
   {
      this.id = id;
      this.room = room;
      this.occupied = occupied;
   }

}