package demo.buildingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Room")
@org.kie.api.definition.type.Description("Represents a Room")
public class Room implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Identifier")
   @org.kie.api.definition.type.Description("room ID")
   private java.lang.String id;
   @org.kie.api.definition.type.Label("Name")
   @org.kie.api.definition.type.Description("Name of the room")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("Size")
   @org.kie.api.definition.type.Description("Size of the room in Sq. Ft.")
   private java.lang.Float size;

   @org.kie.api.definition.type.Label("Building")
   private demo.buildingmanagement.Building building;

   public Room()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Float getSize()
   {
      return this.size;
   }

   public void setSize(java.lang.Float size)
   {
      this.size = size;
   }

   public demo.buildingmanagement.Building getBuilding()
   {
      return this.building;
   }

   public void setBuilding(demo.buildingmanagement.Building building)
   {
      this.building = building;
   }

   public Room(java.lang.String id, java.lang.String name, java.lang.Float size,
         demo.buildingmanagement.Building building)
   {
      this.id = id;
      this.name = name;
      this.size = size;
      this.building = building;
   }
   
   public void turnOnSprinkler() {
       
   }

}