package demo.buildingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Temperature Sensor")
@org.kie.api.definition.type.Description("Represents a Temperature Sensor")
@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
public class TemperatureSensor implements java.io.Serializable
{
   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("id")
   private java.lang.String id;
   @org.kie.api.definition.type.Label("Current Temperature")
   @org.kie.api.definition.type.Description("Current Temperature in F")
   private java.lang.Float value;
   @org.kie.api.definition.type.Label("Time Stamp")
   @org.kie.api.definition.type.Description("Time of measurement")
   private java.util.Date ts;

   @org.kie.api.definition.type.Label("In room")
   private demo.buildingmanagement.Room room;

   public TemperatureSensor()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.Float getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Float value)
   {
      this.value = value;
   }

   public java.util.Date getTs()
   {
      return this.ts;
   }

   public void setTs(java.util.Date ts)
   {
      this.ts = ts;
   }

   public demo.buildingmanagement.Room getRoom()
   {
      return this.room;
   }

   public void setRoom(demo.buildingmanagement.Room room)
   {
      this.room = room;
   }

   public TemperatureSensor(java.lang.String id, java.lang.Float value,
         java.util.Date ts, demo.buildingmanagement.Room room)
   {
      this.id = id;
      this.value = value;
      this.ts = ts;
      this.room = room;
   }

}