package demo.buildingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TemperatureThreshold implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Description(value = "Maximum Value")
   @org.kie.api.definition.type.Label(value = "Maximum Value")
   private java.lang.Float max;

   public TemperatureThreshold()
   {
   }

   public java.lang.Float getMax()
   {
      return this.max;
   }

   public void setMax(java.lang.Float max)
   {
      this.max = max;
   }

   public TemperatureThreshold(java.lang.Float max)
   {
      this.max = max;
   }

}