package demo.buildingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataVServer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DataVServer() {
    }

    public static void triggerWorkflow(String name) {
    }
}