package demo.buildingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FireDetected implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Description(value = "Date/Time fire was detected")
   @org.kie.api.definition.type.Label(value = "Time Stamp")
   private java.util.Date ts;
   @org.kie.api.definition.type.Description(value = "Room fire was detected in")
   @org.kie.api.definition.type.Label(value = "Detected in Room")
   private demo.buildingmanagement.Room room;

   public FireDetected()
   {
   }

   public java.util.Date getTs()
   {
      return this.ts;
   }

   public void setTs(java.util.Date ts)
   {
      this.ts = ts;
   }

   public demo.buildingmanagement.Room getRoom()
   {
      return this.room;
   }

   public void setRoom(demo.buildingmanagement.Room room)
   {
      this.room = room;
   }

   public FireDetected(java.util.Date ts, demo.buildingmanagement.Room room)
   {
      this.ts = ts;
      this.room = room;
   }

}