package demo.buildingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
public class OutsideTemperature implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "OUTSIDETEMPERATURE_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "OUTSIDETEMPERATURE_ID_SEQ", name = "OUTSIDETEMPERATURE_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Time Stamp")
   private java.util.Date ts;

   @org.kie.api.definition.type.Label("Current Temperature")
   private java.lang.Float value;

   public OutsideTemperature()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.util.Date getTs()
   {
      return this.ts;
   }

   public void setTs(java.util.Date ts)
   {
      this.ts = ts;
   }

   public java.lang.Float getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Float value)
   {
      this.value = value;
   }

   public OutsideTemperature(java.lang.Long id, java.util.Date ts,
         java.lang.Float value)
   {
      this.id = id;
      this.ts = ts;
      this.value = value;
   }

}