package demo.buildingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Sprinkler Activated")
@org.kie.api.definition.type.Description("Represents a Sprinkler Activated Event")
public class SprinklerActivated implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Description(value = "Date/Time Sprinkler was activated")
   @org.kie.api.definition.type.Label(value = "Time Stamp")
   private java.util.Date ts;
   @org.kie.api.definition.type.Description(value = "Room in which the Sprinkler was activated")
   @org.kie.api.definition.type.Label(value = "Room")
   private demo.buildingmanagement.Room room;

   public SprinklerActivated()
   {
   }

   public java.util.Date getTs()
   {
      return this.ts;
   }

   public void setTs(java.util.Date ts)
   {
      this.ts = ts;
   }

   public demo.buildingmanagement.Room getRoom()
   {
      return this.room;
   }

   public void setRoom(demo.buildingmanagement.Room room)
   {
      this.room = room;
   }

   public SprinklerActivated(java.util.Date ts,
         demo.buildingmanagement.Room room)
   {
      this.ts = ts;
      this.room = room;
   }

}