package demo.buildingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TemperatureHigh implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Description(value = "Indicate that temperature is high in the room")
   @org.kie.api.definition.type.Label(value = "Room")
   private demo.buildingmanagement.Room room;

   public TemperatureHigh()
   {
   }

   public demo.buildingmanagement.Room getRoom()
   {
      return this.room;
   }

   public void setRoom(demo.buildingmanagement.Room room)
   {
      this.room = room;
   }

   public TemperatureHigh(demo.buildingmanagement.Room room)
   {
      this.room = room;
   }

}