package demo.buildingmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("User")
@org.kie.api.definition.type.Description("Represents a user in the system")
public class User implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "User Id")
   private java.lang.String userid;
   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Roles")
   private java.util.List<demo.buildingmanagement.Role> roles;

   public User()
   {
   }

   public java.lang.String getUserid()
   {
      return this.userid;
   }

   public void setUserid(java.lang.String userid)
   {
      this.userid = userid;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.util.List<demo.buildingmanagement.Role> getRoles()
   {
      return this.roles;
   }

   public void setRoles(java.util.List<demo.buildingmanagement.Role> roles)
   {
      this.roles = roles;
   }

   public User(java.lang.String userid, java.lang.String name,
         java.util.List<demo.buildingmanagement.Role> roles)
   {
      this.userid = userid;
      this.name = name;
      this.roles = roles;
   }

}